### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ocs-wp#130]
- [x] update URLs in database  
- [x] changes as needed for https
- [x] check media and pdf working as expected
- [ ] pdf creation settings
- [x] main element padding
- [x] merge v2 into master

**Comment by pollardld** [comment]
Unidentified obstacles:  
  - server configuration
	- apache and nginx
	- mod_rewrite (permalinks)
	- .htaccess
	- wp-config file
	- wordpress version
  - media urls overwritten in media/.htaccess
  - database cloned from production. had to replicate work done on dev server
	- pdf creation templates
	- slider updates
